[[windup-quickstarts]]
= Windup Quickstarts

Summary: The quickstarts in this repository provide examples of how to create rules for Windup +
Source: https://github.com/windup/windup-quickstarts +

[[introduction]]
== Introduction

These quickstarts provide examples of how to create custom rules for Windup.

[[available-quickstarts]]
== Available Quickstarts

The following is the list of the currently available quickstarts.

. link:ejb-beanutils-async/README.adoc[ejb-beanutils-async]
. link:maven-plugin-usage/README.adoc[maven-plugin-usage]
. link:proprietary-javaee-servlet/README.adoc[proprietary-javaee-servlet]
. link:victi.ms/README.adoc[victi.ms]


[[system-requirements]]
== System requirements

The rules in this repository are designed to be run on Windup 2.x or
later.

This project requires Java 11 (Java SDK 11) or later and Maven 3.0 or
later.

[[install-windup]]
== Install Windup

If you have not installed Windup, follow the instructions here: https://github.com/windup/windup/wiki/Install[Download and Install Windup].


[[use-of-windup_home-variable]]
== Use of WINDUP_HOME Variable

The quickstart README files use the _replaceable_ value `WINDUP_HOME` to
denote the path to the Windup installation. When you encounter this
value in a README file, be sure to replace it with the actual path to
your Windup installation.

[[additional-information]]
== Additional Information

The latest Windup information can be found on the https://github.com/windup/windup/wiki[Windup Wiki].

The Windup documentation is located here: 

* https://github.com/windup/windup/wiki/User-Guide[Windup User Guide]
* https://github.com/windup/windup/wiki/Rules-Development-Guide[Windup Rules Development Guide]
* http://windup.github.io/windup/docs/latest/javadoc[Windup JavaDoc]
* http://windup.jboss.org/schema/windup-jboss-ruleset.xsd[Windup Rule Schema]

To download the latest release of the quickstarts ZIP file, browse to https://github.com/windup/windup-quickstarts/releases.


