[[ejb-beanutils-asyn-windup-rule-that-detects-seam-asynchronous-annotation-in-remote-ejbs]]
= Using Windup Maven Plugin

Author: Marek Novotny, Ondřej Žižka +
Level: Beginner +
Summary: Demonstrates how to execute Windup during a Maven build against the project sources. + 
Source: https://github.com/windup/windup-quickstarts/ +

[[what-is-it]]
== What is it?

This quickstart shows how to use Windup in a Maven project to create reports for migration to Red Hat JBoss Enterprise Application Platform 6.

The quickstart also contains one custom Windup rule in a XML file and shows where to place it to let Windup find it.

The example project contains the Seam `@Asynchronous` annotation which is not compatible with remote EJBs in Red Hat JBoss Enterprise Application Platform and must be replaced with the Java EE 6 `@Asynchronous` annotation.

== How to build this project (run the Windup Maven plugin)

Here is a sequence of commands to run.
[source bash]
------------------------------
git clone https://github.com/windup/windup-quickstarts.git
cd windup-quickstarts/maven-plugin-usage
sed -i -- 's#<version.windup>2.*/version.windup>#<version.windup>2.5.0.CR2</version.windup>#g' pom.xml
mvn install -DskipTests
------------------------------

The `sed` command replaces the version in `pom.xml` with 2.5.0.CR. Change that to the latest Windup release.
