name: Windup Quickstarts PR builder for JDK11

on:
  pull_request:
    branches:
      - master

jobs:

  windup-quickstarts-pr-builder-jdk11:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout windup repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup
          path: windup
      - name: Checkout windup repo
        uses: actions/checkout@v3
        with:
          path: windup-quickstarts
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
          cache: 'maven'
      - name: Build Windup on JDK 11
        run: mvn -B clean install -DskipTests -f windup
      - name: Build on JDK 11
        run: mvn -B clean install -s ./windup-quickstarts/settings.xml -DskipTests -f windup-quickstarts && mvn -B clean install -s ./windup-quickstarts/settings.xml -f windup-quickstarts
        
        
        
