name: Windup Quickstarts PR builder for JDK11

on:
  pull_request:
    branches:
      - master

jobs:

  windup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          repository: windup/windup
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: jdk
          cache: 'maven'
      - name: Build on JDK 11
        run: mvn -B clean install -DskipTests
  
  windup-quickstarts-pr-builder-jdk11:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [windup-build]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: jdk
          cache: 'maven'
      - name: Build on JDK 11
        run: mvn -B clean install -s settings.xml -DskipTests && mvn -B clean install -s settings.xml
        
        
        
