name: Windup Quickstarts PR builder

on:
  pull_request:
    branches:
      - master
      - 'releases/**'

jobs:

  windup-quickstarts-pr-builder-jdk11:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [ 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout windup repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup
          path: windup
          ref: ${{ github.base_ref }}
      - name: Checkout windup-maven-plugin repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup-maven-plugin
          path: windup-maven-plugin
          ref: ${{ github.base_ref }}
      - name: Checkout windup-rulesets repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup-rulesets
          path: windup-rulesets
          ref: ${{ github.base_ref }}
      - name: Checkout windup-quickstarts repo
        uses: actions/checkout@v3
        with:
          path: windup-quickstarts
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
          cache: 'maven'
      - name: Build Windup on JDK 11
        run: mvn -B clean install -DskipTests -f windup
      - name: Build Windup Rules on JDK 11
        run: mvn -B clean install -DskipTests -f windup-rulesets
      - name: Build Windup Maven Plugin on JDK 11
        run: mvn -B clean install -DskipTests -f windup-maven-plugin
      - name: Build on JDK 11
        run: mvn -B clean install -s ./windup-quickstarts/settings.xml -DskipTests -f windup-quickstarts
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          java-package: jdk
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.7
      - name: Test
        run:   |
          if [ "$RUNNER_OS" == "Windows" ]; then
               SET MAVEN_OPTS="--add-modules=java.se  --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.stream=ALL-UNNAMED"
          else
               export MAVEN_OPTS="--add-modules=java.se  --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.stream=ALL-UNNAMED"
          fi
          mvn -B clean install -s ./windup-quickstarts/settings.xml -f windup-quickstarts
        shell: bash
